# Generated by Django 6.0.6 on 2026-06-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
