# Generated by Django 6.0.6 on 2026-06-05 08:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0002_alter_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'user_id')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
