# Generated by Django 6.0.6 on 2026-06-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0004_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,
                                       verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,
                                       verbose_name='Дата создания'),
        ),
    ]
