# Generated by Django 6.0.6 on 2026-06-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager',
         '0008_alter_transaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50,
                                   verbose_name='Название категории'),
        ),
    ]
