# Generated by Django 6.0.6 on 2026-06-07 11:12

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0009_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User,
                                    on_delete=django.db.models.
                                    deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
