# Generated by Django 6.0.6 on 2026-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager',
         '0011_remove_category_amount_alter_category_user_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='Доход',
                                   max_length=10,
                                   verbose_name='Тип'),
        ),
    ]
