# Generated by Django 6.0.6 on 2026-06-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0012_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.
                                    deletion.CASCADE,
                                    related_name='transactions',
                                    to='finance_manager.budget'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.
                                    deletion.CASCADE,
                                    to='finance_manager.category',
                                    verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(verbose_name='Год/Месяц'),
        ),
    ]
