# Generated by Django 6.0.6 on 2026-06-07 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager',
         '0013_transaction_budget_alter_budget_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.
                                    deletion.CASCADE,
                                    related_name='transactions',
                                    to='finance_manager.budget'),
        ),
    ]
