# Generated by Django 6.0.6 on 2026-06-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0014_alter_transaction_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='current',
            field=models.DecimalField(decimal_places=2,
                                      default=0,
                                      max_digits=10),
        ),
    ]
